name = "d1-proxy-service"  # 符合规范的worker名称
main = "index.js"
compatibility_date = "2024-08-01"

# D1数据库绑定配置
[[d1_databases]]
binding = "db"  # 与代码中的env.db对应
database_name = "di2"  # 替换为你的数据库名称
database_id = "f52bb346-b167-4fa3-a27e-f43a95e49af8"  # 替换为你的数据库ID
    
